name: Flutter CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6' # Updated Flutter version

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
